version: '3.9'

services:
  nginx:
    image: nginx
    container_name: nginx
    ports:
      - 9010:80
    restart: unless-stopped
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - $HOST_VOLS/nginx/conf.d:/etc/nginx/conf.d:ro
      - $HOST_VOLS/nginx/log:/var/log/nginx:rw
      - $HOST_VOLS/www:/var/www:ro

  db:
    image: mysql
    container_name: db
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      - MYSQL_ROOT_USER=$MY_DB_USER
      - MYSQL_ROOT_PASSWORD=$MY_DB_PASSWORD
    ports:
      - 3310:3306
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - $HOST_VOLS/db/var/lib/mysql:/var/lib/mysql
    healthcheck:
      test: mysqladmin ping -h 127.0.0.1 -u $$MYSQL_ROOT_USER --password=$MY_DB_PASSWORD
      timeout: 20s
      retries: 3

  api_local:
    image: api_local
    build:
      context: api
    container_name: api_cp_local
    depends_on:
      - db
    env_file:
      - api/.env
