# Generated by Django 4.0.3 on 2022-03-02 21:15

import credit_policy.models.condition
import credit_policy.models.credit_policy
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CreditPolicy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256)),
                ('code', models.CharField(default=credit_policy.models.credit_policy.generate_code, max_length=6, unique=True)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Condition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default=credit_policy.models.condition.generate_code, max_length=256)),
                ('expression', models.CharField(max_length=500)),
                ('is_root', models.BooleanField(default=False)),
                ('t_terminal', models.CharField(max_length=6, validators=[django.core.validators.RegexValidator(regex='ACCEPT|REJECT')])),
                ('f_terminal', models.CharField(max_length=6, validators=[django.core.validators.RegexValidator(regex='ACCEPT|REJECT')])),
                ('rejected_reason', models.CharField(max_length=256, null=True)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('f_child', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='credit_policy.condition')),
                ('policy', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='conditions', to='credit_policy.creditpolicy')),
                ('t_child', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='credit_policy.condition')),
            ],
        ),
        migrations.CreateModel(
            name='Attribute',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('policy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='credit_policy.creditpolicy')),
            ],
            options={
                'unique_together': {('name', 'policy')},
            },
        ),
    ]
