# Generated by Django 4.0.3 on 2022-03-02 21:22

import credit_policy.models.credit_policy
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('credit_policy', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='creditpolicy',
            name='code',
            field=models.CharField(default=credit_policy.models.credit_policy.generate_code, max_length=7, unique=True),
        ),
    ]
