# Generated by Django 4.0.3 on 2022-03-03 12:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('credit_policy', '0002_alter_creditpolicy_code'),
    ]

    operations = [
        migrations.CreateModel(
            name='CreditApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('applicant_name', models.CharField(max_length=255)),
                ('applicant_mobile', models.CharField(max_length=15)),
                ('policy_data', models.JSONField()),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('result', models.JSONField()),
                ('policy', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='credit_policy.creditpolicy')),
            ],
        ),
    ]
