# Generated by Django 4.0.3 on 2022-03-03 21:25

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('credit_policy', '0003_creditapplication'),
    ]

    operations = [
        migrations.AlterField(
            model_name='condition',
            name='f_terminal',
            field=models.CharField(max_length=6, null=True, validators=[django.core.validators.RegexValidator(regex='ACCEPT|REJECT')]),
        ),
        migrations.AlterField(
            model_name='condition',
            name='t_terminal',
            field=models.CharField(max_length=6, null=True, validators=[django.core.validators.RegexValidator(regex='ACCEPT|REJECT')]),
        ),
    ]
