# Generated by Django 4.0.3 on 2022-03-06 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('credit_policy', '0005_creditpolicy_is_complete'),
    ]

    operations = [
        migrations.AddField(
            model_name='attribute',
            name='example_value',
            field=models.CharField(max_length=256, null=True),
        ),
        migrations.AddField(
            model_name='attribute',
            name='type',
            field=models.CharField(choices=[('int', 'NUMBER'), ('str', 'STRING')], max_length=3),
            preserve_default=False,
        ),
    ]
